### ISSUE TITLE
How to open a file in the project?

### ISSUE THREAD

**Issue by guoliang1206** [philipphecht/react-native-doc-viewer#10]
How can I open a file in the path "../app/Resources/Pdfs/test.pdf" ?

**Comment by philipphecht** [comment]
Hey, for Docs on the device you have to you use fs:
npm install fs
var RNFS = require('react-native-fs');
import OpenFile from 'react-native-doc-viewer';
var SavePath = Platform.OS === 'ios' ? RNFS.MainBundlePath : RNFS.DocumentDirectoryPath;
this.setState({file: SavePath + '/' + 'file.pdf'});

in the next version i include it in the dependencies.

**Comment by guoliang1206** [comment]
@philipphecht thank you my friend,I according to your guide and improve my code, I got this:

this is the console log:
![2017-05-16 2 10 37](https://cloud.githubusercontent.com/assets/12846676/26092080/8e1068f8-3a41-11e7-9ec4-afa0255a4745.png)

And it shows a gray background with no pdf files, why it appear this situation?
![simulator screen shot 2017 5 16 2 10 50]
(https://cloud.githubusercontent.com/assets/12846676/26092081/917e14ae-3a41-11e7-9923-59b265d603fb.png)

**Comment by philipphecht** [comment]
Hey @SwordsMan, which Path from react-native-fs do you use?
RNFS.MainBundlePath? When you use this you have add your File in Xcode? Have you done this?

best regards

**Comment by guoliang1206** [comment]
@philipphecht where should I place the pdf.file? on ios, I place it like this:
![2017-05-16 2 32 55](https://cloud.githubusercontent.com/assets/12846676/26092661/c7d39832-3a44-11e7-9bf9-3008d95c5cc2.png)

and I got a console log, it seems correctly like when use http url:
![2017-05-16 2 10 37](https://cloud.githubusercontent.com/assets/12846676/26092675/e0a1d43c-3a44-11e7-804f-8457d0c5bae3.png)

but it not show my pdf file only has gray board.
![simulator screen shot 2017 5 16 2 33 30](https://cloud.githubusercontent.com/assets/12846676/26092697/f731a92a-3a44-11e7-9ff7-ccd3d632ba15.png)

**Comment by philipphecht** [comment]
You have to open Xcode drag the file into the XCODE Project. then it should work. Have you done this?

**Comment by guoliang1206** [comment]
@philipphecht  yeah, I forgot this cause switch the IDE, THANK YOU !!!
