### ISSUE TITLE
"Couldn't issue file extension for path" for every file i'm trying to open

### ISSUE THREAD

**Issue by GaborWnuk** [philipphecht/react-native-doc-viewer#11]
Hi,

currently i have a problem with opening anything with react-native-doc-viewer.

I'm trying to pick a file from iCloud, ending up with following data:

```
[ { url: 'file:///private/var/mobile/Containers/Data/Application/3B8B66C1-F991-4357-9D3B-B740B50039A8/tmp/org.my.app-Inbox/HELP%20resume%20-%20tanner.pdf',
    fileName: 'HELP resume - tanner.pdf' } ]
```

so i'm passing `url` like so:

```javascript
OpenFile.openDoc(
  [
    {
      url: url.uri,
      fileName: url.fileName,
    },
  ],
  (error, url) => {
    if (error) {
      console.error(error);
    } else {
      console.log(url);
    }
  },
);
```

Sadly, everything i'm trying to preview ends up with gray preview view and following log:
```
2017-05-14 19:01:05.642140+0200 CommunityClient[380:36929] [default] Couldn't issue file extension for path: /file:/private/var/mobile/Containers/Data/Application/3B8B66C1-F991-4357-9D3B-B740B50039A8/tmp/org.my.app-Inbox/HELP%20resume%20-%20tanner.pdf #PreviewItem
```

**Comment by philipphecht** [comment]
Hey, for Docs on the device you have to you use fs:
npm install fs
var RNFS = require('react-native-fs');
import OpenFile from 'react-native-doc-viewer';
var SavePath = Platform.OS === 'ios' ? RNFS.MainBundlePath : RNFS.DocumentDirectoryPath;
this.setState({file: SavePath + '/' + 'file.pdf'});

in the next version i include it in the dependencies.
