### ISSUE TITLE
Not Support Chinese ?

### ISSUE THREAD

**Issue by yuchao-wang** [philipphecht/react-native-doc-viewer#112]
if url param contains chinese , it can't run correctly

**Comment by Kylin93CN** [comment]
Can you describe it clearly?

which platform?
url  param like....?

In a word, a little more detail

**Comment by yuchao-wang** [comment]
for example : http://trunk-img.weiboyi.com/vol1/2/101/110/j/l/07pq43r088n711r8o21300505696731p/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20180526162115.png

I can't open this picture through your library

**Comment by yuchao-wang** [comment]
I resolve this problem through this method : `encodeURI()`
