### ISSUE TITLE
Support lazy loading

### ISSUE THREAD

**Issue by liquidprogrammer** [philipphecht/react-native-doc-viewer#12]
Hi, @philipphecht!

I have just tried your plugin and it looks/works pretty well. But, it takes too much time to load big PDF files. What do you think about lazy loading (for doc and for its pages)?
I mean:
1. Open viewer instantly and show some loading bar, while document downloading is in progress
2. When you know the total number of pages - render all of them with spinners, so user will be already able to scroll document down and not just wait for smth
3. When a page ready (parsed or what), replace spinner with page content
You can find an example of that behaviour here: https://mozilla.github.io/pdf.js/web/viewer.html
Are you going to implement this? And when, if so? :)

BTW: Great job! Viewer with already loaded (but takes muck time) document works really good!

**Comment by philipphecht** [comment]
Thank you. It is a good point. I have it on my roadmap.

**Comment by enahum** [comment]
@philipphecht what happended to this? Were you able to implement it?
