### ISSUE TITLE
Android Crash: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by lightnate** [philipphecht/react-native-doc-viewer#130]
The app crash on android emulator and real phone, the photo is from android studio.
<img width="1014" alt="as error@2x" src="https://user-images.githubusercontent.com/18277898/57668500-21471c80-763a-11e9-931a-9f4844179226.png">

This is my code:
```
OpenFile.openDoc([{
  url: data.attachment,
  fileName: data.fileName,
  cache: true,
  fileType
}], (error, url) => {
  if (error) {
    console.log('openDoc err', err)
  }
})
```

Version: 
```
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
"react-native-doc-viewer": "^2.7.8",
```

**Comment by chenxinwahaha** [comment]
how to solve it

**Comment by d-vincent** [comment]
I have this issue, was a solution found?

**Comment by sw-tt-keyurprajapati** [comment]
I am getting the same issue. Reference document URL(https://calibre-ebook.com/downloads/demos/demo.docx) provide in this library exmple no crash happened. Crash happened with our server url only.

**Comment by mcl950121** [comment]
Hello, have you solved it?

> I am getting the same issue. Reference document URL(https://calibre-ebook.com/downloads/demos/demo.docx) provide in this library exmple no crash happened. Crash happened with our server url only.

Hello, have you solved it?

**Comment by mcl950121** [comment]
> 我遇到同样的问题。此库中提供的参考文档URL（https://calibre-ebook.com/downloads/demos/demo.docx）未发生崩溃。只有我们的服务器网址发生了崩溃。
Hello, have you solved it?

**Comment by djl-1022** [comment]
注释掉RNReactNativeDocViewerModule.java第213,214,215行
