### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by loulou1007** [philipphecht/react-native-doc-viewer#14]
Hi 
I'm trying to use react-native-doc-viewer on react web application with visual studio.
I saw the tuto, but I don't understand , I have this error : 

          SyntaxError: import declarations may only appear at top level of a module

This is my code  : 
`import OpenFile from 'react-native-doc-viewer';`
```
handlePress = () => {
    OpenFile.openDoc([{
        url:"http://www.snee.com/xml/xslt/sample.doc",
        fileName:"sample"
   }], (error, url) => {
      if (error) {
        console.error(error);
      } else {
        console.log(url)
      }
    })
}

```
```
<div id="documentViewer">
         {this.handlePress}
</div>
```

How can I do that ? Thank you

**Comment by philipphecht** [comment]
You have a failure in your render method. Try to open it with a button.

**Comment by loulou1007** [comment]
@philipphecht  thank you for your answer, but i added a button ; but i have the same problem .. Someone have an idea ?
