### ISSUE TITLE
Issue opening XLSX file.

### ISSUE THREAD

**Issue by njt1982** [philipphecht/react-native-doc-viewer#18]
This plugin is working fine for Images and PDFs on our API which runs on `/attachment/:id` (where ID is numeric).

```
  _renderAttachment(attachment) {
    const baseUrl = Config.BASE_URL;

    return (
      <ListItem key={attachment.id} onPress={() => OpenFile.openDoc([{url: baseUrl + attachment.download_url, fileName: attachment.file_name}], (error, url) => { if (error) { console.error(error) } }) } >
        <Body style={styles.listItemBody}>
          <Text>{attachment.file_name}</Text>
        </Body>
        <Right><Icon name="arrow-forward" /></Right>
      </ListItem>
    );
  }
```

I have tried adding `fileType:'xls'` and `fileType:'xlsx'` to the openDoc params. No effect.

I am testing out with this file:
https://tcd.blackboard.com/webapps/dur-browserCheck-BBLEARN/samples/sample.xlsx

(comes top of Google for "xlsx example" 😉 )

The attachment object looks like this:

```
{
  content_disposition:"attachment",
  created_at:"2017-07-06T17:09:39.076Z",
  download_url:"/attachments/11",
  file_name:"sample.xlsx",
  id:11,
  mime_type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
}
```

**Comment by njt1982** [comment]
I just uploaded a PNG file and it opens fine:
![image](https://user-images.githubusercontent.com/384976/27924538-951025e8-6279-11e7-9737-c7d8b747ac30.png)

Although I'd like it to use the fileName provided in the params in the header, not the file name on the end of the URL.

**Comment by njt1982** [comment]
Just tried this XLS file and have the same issue: //www.cmu.edu/blackboard/files/evaluate/tests-example.xls

**Comment by njt1982** [comment]
There are no errors (the error arg in the callback is null)... I just get a grey screen like this:

![image](https://user-images.githubusercontent.com/384976/27924675-fb442dfa-6279-11e7-8563-9e546557afd4.png)

**Comment by njt1982** [comment]
Same with DOCX... https://calibre-ebook.com/downloads/demos/demo.docx

**Comment by njt1982** [comment]
Hmm... ok this seems to be our API because if I try to open that URL directly, it works fine...

**Comment by njt1982** [comment]
Ah I dont think this IS a bug in our API :)

**Comment by njt1982** [comment]
https://github.com/philipphecht/react-native-doc-viewer/blob/2195890e7acdcbc8a3e5c7ca649d5b92ddc6f548/ios/RNReactNativeDocViewer.m#L46

In this file, when opening from a URL, we ignore the `fileName`. On line 58, we overwrite the provided `fileName` with the last path component of the URL. In my case, this is the numeric file ID which has no extension. As it has no extention, it seems to assume its a PDF.

```
NSString* fileName = [url lastPathComponent];
NSString* fileExt = [fileName pathExtension];
RCTLogInfo(@"Pretending to create an event at %@", fileExt);
if([fileExt length] == 0){
  fileName = [NSString stringWithFormat:@"%@%@", fileName, @".pdf"];
}
```

**Comment by njt1982** [comment]
This would explain why I get so many of these notices: `Pretending to create an event at `

**Comment by njt1982** [comment]
In fact it looks like the `filename` from `NSString* filename = dict[@"fileName"];` is never actually used anywhere?

**Comment by njt1982** [comment]
So this is either a bug in openDoc OR the documentation needs updating to indicate that my situation should have used `openDocBinaryinUrl`...

For reference, my fix is this:

```
  _renderAttachment(attachment) {
    const baseUrl = Config.BASE_URL;
    let url = attachment.download_url.indexOf('http') === 0 ? attachment.download_url : baseUrl + attachment.download_url

    var parts = attachment.file_name.split('.')
    let fileType = parts.pop();
    let fileName = parts.join('.')

    return (
      <ListItem key={attachment.id} onPress={() => OpenFile.openDocBinaryinUrl([{url, fileName, fileType}], (error, url) => { console.log(error, url); if (error) { console.error(error) } }) } >
        <Body style={styles.listItemBody}>
          <Text>{attachment.file_name}</Text>
        </Body>
        <Right><Icon name="arrow-forward" /></Right>
      </ListItem>
    );
  }
```

**Comment by philipphecht** [comment]
Hey guys thank you for the issue.

**Comment by TrustTheBoy** [comment]
@njt1982 Android can I use it?

**Comment by philipphecht** [comment]
This fixed in IOS

**Comment by akshaygore06** [comment]
I am still facing the same issue on Android.

**Comment by kalpacse96** [comment]
@philipphecht : I am also facing same issue for docx and XLSX. 
@akshaygore06 did you find any work around?
