### ISSUE TITLE
Unable to access local files (Android)

### ISSUE THREAD

**Issue by KartikSubramaniam** [philipphecht/react-native-doc-viewer#22]
Hi I tried to open local files using android emulator but I'am getting an error stating 1.
I have tried it for PDF,JPG,PNG and XLSX types and I got the same result.

The app works fine in case of IOS.

When do you intend to release the same for windows?

**Comment by iRoachie** [comment]
Having this same error as well.  Can you give some guidance here @philipphecht

**Comment by kshreve** [comment]
@KartikSubramaniam @iRoachie  - Are you using OpenFile.openDocb64? This looks to be on the roadmap for Android. If you look [here](https://github.com/philipphecht/react-native-doc-viewer/blob/master/android/src/main/java/com/reactlibrary/RNReactNativeDocViewerModule.java#L92), you can see that the file preview / download activity is commented out for Android currently.

**Comment by iRoachie** [comment]
@KartikSubramaniam No I'm using normal openDoc. I download file using `react-native-fs` to `RNFS.ExternalDirectoryPath` then try to open it. It keep shows error code 1.

It work when loading from remote url though

**Comment by oerestad** [comment]
Same problem. Trying to access a file at this location: /storage/emulated/0/Download/1499685855-turnus_fauske_29052506.pdf
Error state is 1

**Comment by oerestad** [comment]
I had to edit the file filepaths.xml and add one line. But if this is the right way of doing things..... I have no idea.
`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <cache-path name="name" path="." />
    <external-path name="Download" path="Download/"/>
</paths>`

**Comment by iRoachie** [comment]
@oerestad When you edited it, did it work?

**Comment by oerestad** [comment]
Yes it dit work after that.
Also remember to add the file:// prefix to the url
------------
OpenFile.openDoc([{
                    url: "file:/" + filepath,
                    fileName: "viewer",
                }], (error, url) => {
                    if (error) {
                        console.error(error);
                    }
                })

**Comment by iRoachie** [comment]
Thanks man, will give it a shot today
