### ISSUE TITLE
Progress callback?

### ISSUE THREAD

**Issue by njt1982** [philipphecht/react-native-doc-viewer#25]
So I have this setup using NativeBase's ListItem component and onPress it shows the file using `OpenFile.openDocBinaryinUrl`... Before this is called, I set a flag in state to indicate download has started and when the download completes, the 2nd param callback handler in OpenFile.openDocBinaryinUrl is called and I reset the flag in state to hide the spinner. This all works ok for me...

However, it would be nice to know download progress for large files? Like iCloud images have a circular progress pie chart indicator.

Do you think it would be possible to have either an event based callback or a timed one that tells the amount downloaded and file size so we can render progress bars?

**Comment by philipphecht** [comment]
implemented in 2.7.2
