### ISSUE TITLE
Plz support react-native@0.46.4

### ISSUE THREAD

**Issue by farmingoz** [philipphecht/react-native-doc-viewer#35]
i want to support react-native@0.46.4

**Comment by njt1982** [comment]
Or even 0.47.x (given 0.48 is in RC now)

Could also do with accepting the beta branch of react too...

```
error "react-native-doc-viewer#react@16.0.0-alpha.6" doesn't satisfy found match of "react@16.0.0-beta.5"
error "react-native-doc-viewer#react-native@0.44.0" doesn't satisfy found match of "react-native@0.47.2"
```

**Comment by njt1982** [comment]
OR even 0.48.x (given 0.49 is in RC now) ;) 

https://github.com/facebook/react-native/releases

**Comment by philipphecht** [comment]
i update the version in a few days
