### ISSUE TITLE
Activity not found to handle: content://com.reactlibrary.provider/name/xxxx.pdf (application/pdf)

### ISSUE THREAD

**Issue by binlaniua** [philipphecht/react-native-doc-viewer#36]
## simulator 
```
genymotion - Sony Xperia Tablet Z - 4.2.2 api 17
``` 

## usage
```
OpenFile.openDoc([{
                url: `a url return pdf binary byte`,
                fileName:  '',
                fileType: 'pdf',
            }], (error, url) => {
                if (error) {
                    console.error(error);
                } else {
                    console.log(url)
                }
            })
```

**Comment by TrustTheBoy** [comment]
How to solve this problem?

**Comment by dahudson88** [comment]
Hello, 

Has this issue been resolved?  I am getting the below error:
![screen shot 2018-03-07 at 11 35 01 am](https://user-images.githubusercontent.com/31221472/37104786-9b627bde-21fb-11e8-83a8-dbde52a9cc2b.png)

Using the below source.  
 ```
var source  = '/data/user/0/com.offmatapp/files/Paystubs%20-%20Received%20in%20Last%2030%20Days.pdf'

OpenFile.openDoc([{
                url:"file:/" + source,
                fileName: "sample",
                cache: false,
                fileType:'pdf'
            }], (error, url) => {
                if (error) {
                    console.error(error);
                } else {
                    console.log(url)
                }
            })
```

For iOS everything is working fine.  This is just an issue with Android.

Thanks in advance

**Comment by Asalem1** [comment]
Does anyone have a solution to this? I see it's been marked resolved without any notes, would love some insight in overcoming this

**Comment by singhlovey** [comment]
Hi @dahudson88 

I am getting the same issue. How did you solve this?

Please help!
thanks

**Comment by InitialSugar** [comment]
I am getting the same issue. How did you solve this?

Please help!
Thanks

**Comment by amitbravo** [comment]
if there is no pdf viewer in your device e.g any kind of app that can open a pdf, this error rises. error handling is not very good . it actually crash the app , once you install a pdf viewer it goes away.
