### ISSUE TITLE
Use headers for authenthication

### ISSUE THREAD

**Issue by iRoachie** [philipphecht/react-native-doc-viewer#38]
Is there any way to pass in headers or api keys?

**Comment by suhodolskiy** [comment]
@iRoachie How did you decide this question? Thank

**Comment by iRoachie** [comment]
@suhodolskiy I didn't get it done through this library. I used [react-native-fs](https://github.com/itinance/react-native-fs) to download it since that supports headers. I then use it from the local storage.

```js
RNFS.downloadFile({
  fromUrl: link,
  toFile: DownloadPath,
  headers: {
    "API-Key": apiKey,
  },
})
```
