### ISSUE TITLE
Content Provider issue

### ISSUE THREAD

**Issue by OisinOKeeffe** [philipphecht/react-native-doc-viewer#40]
Hi guys, noticed since the 2.4.6 update you cannot have different flavors of the same app installed one device due to conflicting com.reactlibrary.provider settings from your module.

Would be great if you supported applicationIdSuffix or something of the kind to prevent this issue.

To reproduce the issue:
- install app with id com.yourapp.dev
- try install app with id com.yourapp.prod and it will fail

**Comment by sraka1** [comment]
https://github.com/philipphecht/react-native-doc-viewer/blob/f01534cce207acfc94fe32e3c1f146bd094bb5f3/android/src/main/AndroidManifest.xml#L5

and 

https://github.com/philipphecht/react-native-doc-viewer/blob/f01534cce207acfc94fe32e3c1f146bd094bb5f3/android/src/main/AndroidManifest.xml#L5

"com.reactlibrary.provider" <- this should be settable as an option somehow. @philipphecht
