### ISSUE TITLE
open mp4 show error!!! Path determination is not a problem

### ISSUE THREAD

**Issue by TrustTheBoy** [philipphecht/react-native-doc-viewer#43]
<img width="268" alt="6aae45db-9704-4d2b-9f86-c9f1cf7a6be3" src="https://user-images.githubusercontent.com/20201085/30194339-2a70aaac-9418-11e7-9f43-374208508489.png">
![image](https://user-images.githubusercontent.com/20201085/30194361-49e3f97a-9418-11e7-8985-054a70145139.png)

**Comment by philipphecht** [comment]
Use fs!
