### ISSUE TITLE
android doc open error!!

### ISSUE THREAD

**Issue by TrustTheBoy** [philipphecht/react-native-doc-viewer#44]
![image](https://user-images.githubusercontent.com/20201085/30202298-8ad40f12-9443-11e7-8295-d227fd887d2d.png)

```  
handlePress = () => {
   OpenFile.openDoc([{
     url:"http://xxxxxx/201709/1504839653822.docx",
     fileName:"sample",
      fileType: 'docx',
   }], (error, url) => {
      if (error) {
        console.error(error);
      } else {
        console.log(url)
      }
    })
  }
```

**Comment by TarasDumych** [comment]
@TrustTheBoy https://github.com/philipphecht/react-native-doc-viewer/issues/8

**Comment by TrustTheBoy** [comment]
I've already seen, but Android plugin is not yet released, and now out of third parties open, the application still can not open, and open on the wrong, and no pop-up third parties available @TarasDumych

**Comment by TrustTheBoy** [comment]
@TarasDumych Do you have a demo case of Android? I see only img and other formats are wrong
