### ISSUE TITLE
OpenFile is undefined on Android

### ISSUE THREAD

**Issue by teacher987** [philipphecht/react-native-doc-viewer#49]
# Versions in use
react-native: 0.48.3,
react-native-doc-viewer: 2.4.7,

# Bug description
Everything works fine on iOS.
I tried both auto linking and manual install for Android, but in either case, _OpenFile_ is undefined.

# Relevant code
```
import OpenFile from 'react-native-doc-viewer';

OpenFile.openDocBinaryinUrl([{
    url:"http://mail.hartl-haus.at/uploads/tx_hhhouses/{binaryString}",
    fileName:"sample",
    fileType:"jpg"
}], (error, url) => {
    if (error) {
        console.error(error);
    } else {
        console.log(url)
    }
});
```

# Error message

> undefined is not a function (evaluating '_reactNativeDocViewer2.default.openDocBinaryinUrl')

Also, the example application keeps crashing, so I can't test with that.

Thanks in advance!

**Comment by chronixlo** [comment]
openDocBinaryinUrl() isn't implemented on android

**Comment by teacher987** [comment]
Thanks for the reply. Are you aware of it being planned for implementation?

**Comment by chronixlo** [comment]
Just found this package recently but it doesn't seem to be developed actively.

Currently trying to solve this with react-native-fs and the [Linking](https://facebook.github.io/react-native/docs/linking.html).openURL() but haven't gotten it working yet

**Comment by teacher987** [comment]
From what I've seen, this package has the most commits and they're more recent than any alternative, but yeah, the last one is from (beginning of) August.

**Comment by philipphecht** [comment]
Android Release next week. Verison 2.5.5
