### ISSUE TITLE
Recent PRs broke the Android build

### ISSUE THREAD

**Issue by sraka1** [philipphecht/react-native-doc-viewer#55]
What needs to be changed in RNReactNativeDocViewerModule.java. I'd open a PR, but am extremely busy in the next couple of days...

1.  ```if (fileName.indexOf("\.") == -1) ``` should be  ```if (fileName.indexOf("\\.") == -1){ ```

2. 
 ```private final Callback callback;
private final String url;
private final String fileName; 
```

to

 ```private final Callback callback;
private final String url;
private final String fileName;
private final Boolean cache; 
```

3.
 ```super();
this.callback = callback;
this.url = url;
this.fileName = fileName; 
```
to
 ```super();
this.callback = callback;
this.url = url;
this.fileName = fileName;
this.cache = cache; 
```

**Comment by sraka1** [comment]
@philipphecht

**Comment by philipphecht** [comment]
Hey, in this week i will update react-native and fix this pr issue. Thanks for your report

**Comment by philipphecht** [comment]
This issue is fixed.
