### ISSUE TITLE
Android crash - error couldn't find key cache in dynamic object

### ISSUE THREAD

**Issue by zivchen** [philipphecht/react-native-doc-viewer#58]
Hi
Im getting an error while trying to open docs (www) throw android,
Error says error couldn't find key cache in dynamic object
you can see it with the readme example of openDo method

**Comment by philipphecht** [comment]
Load  the new Version 2.5.8

**Comment by zivchen** [comment]
Still the same error couldn't find key cache in dynamic object
Installed version 2.5.8 and recompiled all.
I have tried both my own http pdf and the example one, both give the same error
OpenFile.openDoc([{
     url:"http://www.snee.com/xml/xslt/sample.doc",
     fileName:"sample",
     fileExt:"",
     fileType:""
   }], (error, url) => {
      if (error) {
        console.error(error);
      } else {
        console.log(url)
      }
    })

![screen shot 2017-11-22 at 19 12 20](https://user-images.githubusercontent.com/983093/33140798-b294a672-cfb9-11e7-89fb-baa3537a1ef5.png)

**Comment by philipphecht** [comment]
Sorry the readme only includes the ios part, i have uploaded the android part. Version 2.6.0

**Comment by zivchen** [comment]
Thanks, 
Now i got a new issue
When trying to get http pdf i get this error :
ExceptionsManager.js:73 Activity not found to handle: content://com.reactlibrary.provider/name/PP_1206215886.pdf (application/pdf)

this is the way i try to get the file
OpenFile.openDoc(
            [
              {
                url:
                  'http://che.org.il/wp-content/uploads/2016/12/pdf-sample.pdf',
                fileName: 'test',
                cache: false,
                fileType: 'pdf'
              }
            ],
            (error, url) => {
              if (error) {
                console.error(error)
              } else {
                console.log(url)
              }
            }
          )

**Comment by philipphecht** [comment]
Please read the readme, at the moment it is not possible to open a pdf In the app. You have to install a external application to open the pdf.

Von meinem iPhone gesendet

**Comment by ismnoiet** [comment]
@philipphecht Thank you releasing this project to the open source community.
I'm using the `2.6.3` version and the issue still persists.
After some googling the solution seems to be the `cache` key must be present in the config object passed to `OpenFile.openDoc` **now it is working for me after adding cache key**.

In short terms if you get the error `couldn't find key xxx in dynamic object` go make sure you have the key `xxx` defined in `OpenFile.openDoc` config object.

Dropped my comment here to help future questions about this issue.
