### ISSUE TITLE
Library Issue

### ISSUE THREAD

**Issue by rutul0608** [philipphecht/react-native-doc-viewer#60]
Hello,

I recently downloaded your project but i'm not having any libraries in the project. So can you please help me how to get those libraries and libRNReactNativeDocViewer.a file.

Kindly please update me asap. Waiting for your response.
![screen shot 2017-12-01 at 12 51 55 pm](https://user-images.githubusercontent.com/11498492/33472070-7ce858dc-d696-11e7-9298-5358098d79ad.png)

**Comment by philipphecht** [comment]
i have to run npm install & react-native link to install the library in the example Folder or in your own Project Folder

**Comment by rutul0608** [comment]
/Users/rutul/Downloads/react-native-doc-viewer-master/example/DocumentViewerExample/ios/DocumentViewerExample/AppDelegate.m:12:9: 'React/RCTBundleURLProvider.h' file not found.

Can u please help me with this? i've manually added all the things n the steps.

**Comment by philipphecht** [comment]
Delete the node_modules Folder in the Example Folder. Run: npm install and then: react-native link

**Comment by rutul0608** [comment]
can u please tell me what is react-native link coz it's totally a new thing for me n i don't know which command u'r talking about!

**Comment by philipphecht** [comment]
Ok. Please read the react native doc. I explain it to you:
1. Open Windows or Mac Shell window
In the Shell Commands:
2. cd PathtoTheExample Project
3. npm install
4. react-native link

**Comment by rutul0608** [comment]
bro in the last react-native command i got the message that command not found.
"react-native: command not found".
That's why i'm asking you. All other steps are done. Just the last step is showing me an error.

**Comment by philipphecht** [comment]
Ok. I think you dont have installed node and nom on your MAC.

Please download Node Version 7.10.1 here: https://nodejs.org/en/download/releases/
and install it. 

And then in the shell install React native:
npm install -g react-native-cli
npm install -g create-react-native-app

now it should work. With the steps i mentioned above. Do you have Teamviewer i can install it for you on your mac.

**Comment by rutul0608** [comment]
sure! i'm giving you  
my id - 351 201 648

**Comment by rutul0608** [comment]
password - f268xy

**Comment by philipphecht** [comment]
I think in 45 min i can install it for you.

**Comment by philipphecht** [comment]
do have this time?

**Comment by philipphecht** [comment]
i delete the comments from you with the id and password from the teamviewer. You can also mail me the credentials for teamviewer. philipp.hecht@icloud.com

**Comment by philipphecht** [comment]
i need your pass i be back

**Comment by rutul0608** [comment]
hi,
The rest things have been done and executed the code. Thank you so much for your support.
Now will you please assist in one more thing?
In your code the data is coming from the live URL what if i wants to open any type of data from the device.
can you help me in that?
