### ISSUE TITLE
ios Build Fails 

### ISSUE THREAD

**Issue by amitbravo** [philipphecht/react-native-doc-viewer#67]
"react-native-doc-viewer": "^2.7.0",
"react-native": "^0.51.0",
"react": "^16.2.0",
OS: High Sierra 10.13.2
Xcode: 9.2

![screen shot 2017-12-28 at 6 46 51 pm](https://user-images.githubusercontent.com/16644357/34411940-109e25a6-ec00-11e7-8c60-b06acfcb274d.png)

** BUILD FAILED **

Terminal Error: 

The following build commands failed:
CompileC /MyAPP/ios/build/Build/Intermediates.noindex/RNReactNativeDocViewer.build/Debug-iphonesimulator/RNReactNativeDocViewer.build/Objects-normal/x86_64/RNReactNativeDocViewer.o RNReactNativeDocViewer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by philipphecht** [comment]
Hi Andrew, this issue is fixed 2.7.1. Thanks for your report.

**Comment by amitbravo** [comment]
Its perfect with 2.7.1 now but, I do not see file content on device but emulator showing it well , I am using iphone 5s to test, there is no error modal appears but instead of file content, it goes blank, tested a pdf and .txt file .

**Comment by philipphecht** [comment]
Hi Andrew I have no iPhone 5s but I try it with a iPhone 6. Give feedback.

Von meinem iPhone gesendet

**Comment by amitbravo** [comment]
I am stupid, I was prefixing url 'file://' with ios , when I removed the prefix , it works on device as well, prefixing is must with android though.
There is one another benefit of using this library I came to know is  as I was using react-native-photo-view for pinch in zoom feature to display images in larger size, I do not need to use that any more . react-native-doc-view handles this easily , :) 👍
