### ISSUE TITLE
console.error: 1

### ISSUE THREAD

**Issue by mperezrojas** [philipphecht/react-native-doc-viewer#7]
In android i had this error when try to open a local file.
![captura de pantalla 2017-04-11 a las 12 01 16](https://cloud.githubusercontent.com/assets/7092957/24903917/29f95184-1eaf-11e7-8324-1285d61ba3fe.png)
`handlePress = () => {
   OpenFile.openDoc([{
     url:"/Users/iosdev/Desktop/readers/react-native-doc-viewer-master/example/DocViewerExample/ios/ACOXXEL_FICHA_TECNICA.pdf"
   }], (error, url) => {
      if (error) {
        console.error(error);
      } else {
        console.log(url)
      }
    })
  }`

**Comment by mperezrojas** [comment]
If I add this line `fileName:"ACOXXEL_FICHA_TECNICA.pdf"`
the error is 1
<img width="431" alt="captura de pantalla 2017-04-11 a las 12 12 44" src="https://cloud.githubusercontent.com/assets/7092957/24904261/3231d848-1eb0-11e7-9728-278d04c9267a.png">

**Comment by philipphecht** [comment]
You have to set the path of your android device.
So you have to use fs for react native.
https://github.com/johanneslumpe/react-native-fs/blob/master/README.md

**Comment by davidrojo** [comment]
Sorry for opening this, but I am having the same issue, and I don't know what you mean with "You have to set the path of your android device."

I am downloading a file with RNFS, and it downloads correctly, and I can check it has been downloaded with the stat funciton of RNFS. I've already done the "react-native link react-native-fs" and "react-native link react-native-doc-viewer" but I keep receiving the error 1 error message.

```
> react-native link
Scanning 698 folders for symlinks in C:\Users\David\Documents\React-Projects\Ases\node_modules (39ms)
rnpm-install info Android module react-native-doc-viewer is already linked
rnpm-install info iOS module react-native-doc-viewer is already linked
rnpm-install info Android module react-native-fs is already linked
rnpm-install info iOS module react-native-fs is already linked
rnpm-install info Android module react-native-vector-icons is already linked
rnpm-install info iOS module react-native-vector-icons is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
```

And this is the code I use:

```
   OpenFile.openDoc([{
      url: this.props.download.localFile,
      fileName: this.props.download.filename
    }], (error, url) => {
      if (error) {
        console.error("Error", error);
      } 
      else {
        console.log(url);
      }
    });
```

this.props.download.localFile = "/data/user/0/com.ases/files/tmp/Esquemas 2.pdf"
this.props.download.filename = "Esquemas 2.pdf"

**Comment by philipphecht** [comment]
Hey I look at this, the component on android gets a bigger update.

**Comment by davidrojo** [comment]
Thanks @philipphecht, which is the estimated time for the update to be available?

**Comment by paritosh-yadav** [comment]
Hey guys, any update on this. I'm still getting the issue.

**Comment by Grandmac** [comment]
I resolve the issue by adding "file://" at the beginning of file Path for android device
