### ISSUE TITLE
[iOS] fileNameOptional doesn't work when open file in storage directly

### ISSUE THREAD

**Issue by chen2584** [philipphecht/react-native-doc-viewer#70]
It still open anywhere

```
openFileViaStorage(filename, extension, title) {

        //filename = "1516012203338"
       //extension = "png"
      //title = "sample-title"

        filename = `${filename}${extension != "" ? `.${extension}` : ""}`;
        path = `${RNFS.DocumentDirectoryPath}/${filename}`;
        OpenFile.openDoc([{
            url: path,
            fileNameOptional: title,
        }], () => { });
}
```
**Screenshot**
![screen shot 2561-01-15 at 17 32 45](https://user-images.githubusercontent.com/31945018/34938398-cd6b1f54-fa1a-11e7-95b5-a995ff43b21f.png)

**Comment by LeMinh1995** [comment]
Hi @philipphecht , I have made some changes to fix this issue. Can you review in a pull request? Thanks.

**Comment by philipphecht** [comment]
Yes of course. I have at this time no free time  to finish this project. 

Von meinem iPhone gesendet
