### ISSUE TITLE
Works on Simulator but not on Real Device

### ISSUE THREAD

**Issue by dahudson88** [philipphecht/react-native-doc-viewer#75]
I am running into an issue where I am trying to display a local file to my app.  When I am using the Simulator I get the actual pdf displaying.  How ever when I try to run this on a real device, I get the below screen.  Any idea wha maybe causing this?

```
 OpenFile.openDoc([{ 
                url:documentToView,
                fileNameOptional: "sample"
            }], (error, url) => {
                if (error) {
                    console.error(error);
                }
            })
        } else {
            //Android
            OpenFile.openDoc([{
                url: documentToView,
                fileName: "sample",
                cache: true /*Use Cache Folder Android*/
            }], (error, url) => {
                if (error) {
                    console.error(error);
                }
            })
        }
```

**On Simulator**
![simulator screen shot - iphone x - 2018-02-15 at 16 44 38](https://user-images.githubusercontent.com/31221472/36282554-884a19d0-126f-11e8-8da9-5f4c2903b9e7.png)

**On Real Device**
![9155](https://user-images.githubusercontent.com/31221472/36282531-76e391bc-126f-11e8-9b84-ffa638edb495.jpg)

 It may be something with my how I am saving the file.  I am getting a base64 string from a server and then saving it using fetch-blob

```
var RNFetchBlob = require('react-native-fetch-blob').default;
var RNFS = require('react-native-fs');
    var DocumentDir = Platform.OS === 'ios' ? RNFS.MainBundlePath : RNFS.DocumentDirectoryPath;

 RNFetchBlob.fs.writeFile(DocumentDir+'filename', pdf_base64Str, 'base64');
        return {
            status: response.status,
            data: pdfLocation
        }

```

**Comment by philipphecht** [comment]
Have u set in Xcode APP Transport Security Settings -> Allow Arbitrary Loads to YES?

**Comment by dahudson88** [comment]
Thanks for the tip.  I am not sure what changed.  But I came in this morning and now it is working on both the phone and simulator.  This is a great module.  Thanks man!
