### ISSUE TITLE
iOS Microsoft Excel 97-2004 worksheet

### ISSUE THREAD

**Issue by a728384698** [philipphecht/react-native-doc-viewer#80]
![6fb70167-d7fe-45c8-8072-53be7f53146b](https://user-images.githubusercontent.com/7380874/37396790-de6d3f36-27b4-11e8-8736-98ede7696b15.png)

导出的Excel有内容，但是在上面查看就变成这样！没有搞懂为什么？

**Comment by philipphecht** [comment]
I look at this.

**Comment by philipphecht** [comment]
It works.

**Comment by wenjianli92** [comment]
I have encountered the same problem, how do you solve it?

**Comment by cindyya** [comment]
I have encountered the same problem, how do you solve it?
