### ISSUE TITLE
Build crash: 'React/RCTEventEmitter.h' file not found in RNReactNativeDocViewer.h

### ISSUE THREAD

**Issue by mrikirill** [philipphecht/react-native-doc-viewer#81]
Hi there,

I can't build my project (based on ExpoKit) after installation DocViewer module. All steps have been done by following the instruction.
It returns: 'React/RCTEventEmitter.h' file not found in RNReactNativeDocViewer.h 
[Screenshot](https://screencast.com/t/0ZIU3wi9Ww)
Can someone help me ?

RN: 0.52.0
ExpoKit: 2.3.3

**Comment by kridoe** [comment]
Hi @mrikirill,
have you solved the problem? I having same issue too..

**Comment by mrikirill** [comment]
Hi @kridoe 

I've spent a day by trying to resolve it, but still have this issue((
I've tried [this solution](https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found) But it didn't work for me. 
I found that the file **RCTEventEmitter.h** is located in $(SRCROOT)/../node_modules/react-native/React/Modules. Add this path to Header Search Path of Build Section in Xcode but it did't work
