### ISSUE TITLE
Android: stopped working on Android after the update

### ISSUE THREAD

**Issue by JosimarGomes** [philipphecht/react-native-doc-viewer#84]
react-native-doc-viewer stopped working on Android after the update. I solved installing the older version (2.7.3), but I found it good to warn. Sorry for my bad english.

My package.json
 "react": "16.0.0",
 "react-native": "0.50.4",
 "react-native-doc-viewer": "^2.7.3",

**Comment by philipphecht** [comment]
I fix it today.

**Comment by philipphecht** [comment]
Not a Bug.
