### ISSUE TITLE
Dont show document

### ISSUE THREAD

**Issue by chaotzu** [philipphecht/react-native-doc-viewer#9]
When I try to view the document from the internet, the url is displayed in console but does not load the document on screen and this message also appears in console "DATA nil"

When i use with image base 62 it works great

**Comment by philipphecht** [comment]
what filetype is the document you want to show over the internet?

**Comment by chaotzu** [comment]
i try with png, pdf and jpg

**Comment by philipphecht** [comment]
Can you send me one link that not work?

**Comment by chaotzu** [comment]
In my case with any url, including example
![captura de pantalla 2017-05-17 a la s 11 36 05](https://cloud.githubusercontent.com/assets/5109143/26165431/9005db70-3af5-11e7-8408-7e89ee3da8e1.png)

**Comment by philipphecht** [comment]
I will check this.

**Comment by philipphecht** [comment]
Do you this function?

handlePress = () => {
   OpenFile.openDoc([{
     url:"http://mail.hartl-haus.at/uploads/tx_hhhouses/htf13_classic153s(3_giebel_haus).jpg",
     fileName:"sample"
   }], (error, url) => {
      if (error) {
        console.error(error);
      } else {
        console.log(url)
      }
    })
  }

**Comment by MIFind** [comment]
I have a same question.

**Comment by kas84** [comment]
I am just trying out this module and works fine. Are you using https or http? By default apple doesn't allow http. Try this example pdf https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf and see if that works.

**Comment by philipphecht** [comment]
Or this: When you Show http Links don't forget to set Xcode APP Transport Security Settings -> Allow Arbitrary Loads to YES
Stands in the readme;-)

**Comment by DoubleOK** [comment]
I've got the same issue. Xcode APP Transport Security Settings is set to allow arbitrary loads. 

Some files work particularly if they end in a file extension, however, I have some other URLs (which I have verified as working otherwise) that result in data Nil. The urls in question are AWS s3 signed urls if that helps

**Comment by nikhildaga** [comment]
I am facing same problem as @DoubleOK

**Comment by mawansui** [comment]
Hey guys, I have run into kinda the same issue lately: the link was ok and allowed downloading the file in the browser, however, the awesome **react-native-doc-viewer** package could not open it for whatever reason. Xcode console output was like this: `Doc Url not found`.

Nevertheless, the test pdf file, link to which was provided by @kas84, opened perfectly! 

Then I have noticed that my link had a `space` symbol in it, which resulted in the link looking like following: `https://www.some.stuff/03%202017.pdf`. What I did was rename the file to make the link look like this: `https://www.some.stuff/03_2017.pdf`. And now everything opens fine!

So what I am saying is maybe the format of the link plays a role in whether or not a file will open from the link?

Anyway, I really enjoy this package, it is awesome! Thanks to @philipphecht for creating it!

P.S.: BTW, I use RN 0.46 and develop for iOS, if this is of any help.

Cheers!

**Comment by dmitryou** [comment]
Stuck with this module pretty long time.
There are 4 main problems in this module and they still exists:
1.Encoded characters in url (%20- spaces, etc.) will not allow you to open files.
Solution : Make some function to decode those characters and use url without it.
Url string like : 'https://my-downloads/filename%204'.----> should be: 'https://my-downloads/filename 4'
try {
    const decodedUrl = decodeURI(uri);
    return decodedUrl;
  } catch (e) { // catches a malformed URI
    return null;
  } 

2.If you don't provide file extension like(.jpg,.pdf, .png) in IOS at the end of url it won't open it.
3.Already mentioned - Xcode APP Transport Security Settings
4.And finally sometimes it wont open urls - reason not clear.
For example:
https://cdn.filepicker.io/api/file/4OvM7Y5ETEqYg39HB3SA
