### ISSUE TITLE
libRNReactNativeDocViewer.a file is not found in iOS release build

### ISSUE THREAD

**Issue by Diwei-Chen** [philipphecht/react-native-doc-viewer#99]
Hi there,

When I build the app(release) with the library, I get the following error message:

```
No such file or directory: '/Users/xxx/Library/Developer/Xcode/DerivedData/buzzy_rn-cfwqzoriweeqllhfpnlhytuawnrm/Build/Products/Release-iphoneos/libRNReactNativeDocViewer.a'
```

I am sure I followed the manual setup steps and added `libRNReactNativeDocViewer.a` to my project's `Link Binary With Libraries` module.

Any ideas, please?

**Comment by vault13tech** [comment]
did you solved this problem??
